### ISSUE TITLE
Q3/After Q3

### ISSUE THREAD

**Issue by ThijsNameIsTaken** [MooNag/steam-deck-calculator#10]
The first reports showing reservation dates of Q3/After Q3 are in, but the website does not support these dates yet.
![image](https://user-images.githubusercontent.com/19609431/157117858-96f1efca-012e-483b-9f18-f4fd5ee12517.png)
Another screenshot [here](https://www.reddit.com/r/SteamDeck/comments/t8ult6/emotional_damage/) (r/SteamDeck)
Date is visible on the store page while logged out.

**Comment by MooNag** [comment]
Added to the toggle

Moo model is agnostic of Quarter dates. Form was also updated
