### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by OhneNik** [MooNag/steam-deck-calculator#2]
Hey there, 

unfortunately some users didn't seem to correctly answer all the survey questions. E.g. 
<img width="888" alt="image" src="https://user-images.githubusercontent.com/6363433/153683767-ee3e8b00-710e-45ab-90a4-f6feca18dc75.png"> is pretty in the future. But nevertheless - should be an easy fix: just ignore timestamps from the future :) 

Regards

**Comment by MooNag** [comment]
Should be fixed in the form now!
