### ISSUE TITLE
Previous Submissions/File Storage

### ISSUE THREAD

**Issue by anon-0racle** [MooNag/steam-deck-calculator#24]
This may not be a real "issue", but more or less I had a question regarding accuracy and how previous uploads by users may be stored in order to make calculation "easier".

Are uploads made by a user or the same user stored? For example, if I upload a copy of the preorder information on one day, is that kept on a file-server or something similar to that for historical purposes? Similarly, if I upload something another day, is the data previously uploaded overwritten? 

My main concern is that anything uploaded might be stored and could lead to a large influx of stored data possibly consuming server resources (if thats how this is configured). I also see that cookies are stored, so maybe thats the only data that is personally related to a user.

If these concerns are better suited elsewhere feel free to let me know. I apologize if this may seem like a dumb question, but it was something I thought about when using this tool recently.

**Comment by MooNag** [comment]
The site is statically hosted on Firebase Hosting; so the server has no state and doesn't "upload" a copy of the files. Everything is done locally on the browser. Google Sheets takes care of file history if that is needed. The site uses local storage to save their last input so it gets restored each time they open the site. Nothing is sent to any servers, though. Does that satisfy your questions?

**Comment by anon-0racle** [comment]
That makes perfect sense and answers all the questions I had. Thank you!
